server:
  port: 8093  #端口
  tomcat:
    uri-encoding: UTF-8   #服务编码
spring:
  profiles:
    active: "${SPRING_PROFILES_ACTIVE:local}"
  application:
    name: data-service
tj:
  swagger:
    enable: true
    enableResponseWrap: true
    package-path: com.tianji.data.controller
    title: 智能在线教育系统 - 数据中心接口文档
    description: 该服务包含数据看板统计的功能
    contact-name: lfeternity
    contact-url: https://github.com/lfeternity/Smart-Online-Education
    version: v1.0
  jdbc:
    database: tj_data
  auth:
    resource:
      enable: true
