server:
  port: 8085  #端口
  tomcat:
    uri-encoding: UTF-8   #服务编码
spring:
  profiles:
    active: "${SPRING_PROFILES_ACTIVE:local}"
  application:
    name: message-service
tj:
  swagger:
    enable: true
    enableResponseWrap: true
    package-path: com.tianji.message.controller
    title: 智能在线教育系统 - 消息中心接口文档
    description: 该服务用于站内信、通知管理、短信发送等功能
    contact-name: lfeternity
    contact-url: https://github.com/lfeternity/tjxtai
    version: v1.0
  auth:
    resource:
      enable: true
      excludeLoginPaths:
        - /students/register
        - /users/detail/{isStaff}
        - /users/list
        - GET:/users/{id}
        - /users/{id}/type
        - /users/ids
  jdbc:
    database: tj_message
  sms:
    ali:
      accessId: "${ALIYUN_SMS_ACCESS_KEY_ID:}"
      accessSecret: "${ALIYUN_SMS_ACCESS_KEY_SECRET:}"
